# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - CashManagement-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Frontend Dependencies & Build
        run: |
          cd frontend
          npm install
          npm run build

      # buildフォルダをbackendに移す作業は「frontend/package.jsonのpostbuild」で実施する前提

      - name: Prepare Deployment Package (wwwroot配下にまとめる)
        run: |
          mkdir -p deploy_package/wwwroot
          cp -r backend/build deploy_package/wwwroot/
          cp backend/server.js deploy_package/wwwroot/
          cp backend/package.json deploy_package/wwwroot/
          cp backend/package-lock.json deploy_package/wwwroot/
          cd deploy_package
          zip -r ../release.zip wwwroot/

      - name: Upload Artifact for Deployment Job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip Artifact for Deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_989B12E37A4342A9AB3E09A7AAE73CB4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BCE534E2200D4DB68890EE37C619A7FF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1A048D6CAACF466DB634F3F5575E142A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CashManagement-App'
          slot-name: 'Production'
          package: ./wwwroot

      - name: Post-Deployment SSH: npm install
        run: |
          curl -u ${{ secrets.AZURE_APP_DEPLOY_USER }}:${{ secrets.AZURE_APP_DEPLOY_PASSWORD }} \
          -X POST "https://$APP_NAME.scm.azurewebsites.net/api/command" \
          -H "Content-Type: application/json" \
          -d '{ "command": "cd site/wwwroot && npm install" }'
        env:
          APP_NAME: 'CashManagement-App'
