# Azure Web Apps への backend のみデプロイ
# 参考: https://github.com/Azure/webapps-deploy

name: Deploy backend to Azure Web App - CashManagement-App

on:
  push:
    branches:
      - main  # mainブランチに push されたらデプロイ
  workflow_dispatch:  # 手動実行可能

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # actions/checkout に必要

    steps:
      - name: 📥 GitHub リポジトリをクローン
        uses: actions/checkout@v4

      - name: 🔧 Node.js 環境をセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 📦 依存関係をインストール (backend のみ)
        run: |
          cd backend
          npm install

      - name: 📤 backend をアップロード (アーティファクト)
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write  # JWT の発行に必要
      contents: read  # actions/checkout に必要

    steps:
      - name: 📥 backend のビルド成果物をダウンロード
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: 🔑 Azure にログイン
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 🚀 backend を Azure Web Apps へデプロイ
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'CashManagement-App'  # Azure上のWebアプリ名
          slot-name: 'production'
          package: ./backend  # backend のみをデプロイ

      - name: ✅ デプロイ完了メッセージ
        run: echo "🎉 Azure Web App 'CashManagement-App' に backend のみデプロイ完了！"
